### ISSUE TITLE
Custom extension 5min timeout

### ISSUE THREAD

**Issue by jermth** [Azure/custom-script-extension-linux#139]
Hi,

This is in reference to issue [135](https://github.com/Azure/custom-script-extension-linux/issues/135)

WALinuxAgent is version 2.2.29 but I still see this timeout after 300s:
```text
2018/07/23 02:21:26.114648 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.6] Enable extension [bin/custom-script-shim enable]
2018/07/23 02:26:26.444870 WARNING [Microsoft.Azure.Extensions.CustomScript-2.0.6] [ExtensionError] Timeout(300): bin/custom-script-shim enable
[stdout]
```

Again, I only see this in North Central US. My other deployments I tested were in East US and West US2. Neither had this timeout.

Attached is the waagent log. 

Thanks.

[northcentralus.waagent.log](https://github.com/Azure/custom-script-extension-linux/files/2217773/northcentralus.waagent.log)

**Comment by boumenot** [comment]
Is this the same issue as #135?  If so, for the future please re-open the original issue instead of creating a new one.  It makes it easier to track.

Would you please attach /var/log/azure/custom-script/handler.log too.  I see some of that file in the output, but I would prefer to have the full file.  

How long does it take for your script to execute?

**Comment by boumenot** [comment]
This is an agent bug, not an extension bug.  I opened an issue against the agent, and I am closing this one.  Please monitor the agent issue for updates.
