### ISSUE TITLE
CSE execution behavior wrt backgrounds

### ISSUE THREAD

**Issue by rvvincelli** [Azure/custom-script-extension-linux#61]
Hello,

I am sorry to open an issue as a question, I was encouraged to do so by the Microsoft colleague we work with.

Let's say I invoke with the CSE a script like:

```bash
#!/bin/sh                                                                           

do_something() {
    echo Doing stuff
    sleep 2
}

do_something_taking_a_long_time() {
    echo Doing more stuff
    echo In the background
    sleep 10
    echo Still here
    sleep 10
    echo And again
}

do_something

do_something_taking_a_long_time &
```

Will the control return to the setup as expected, possibly finishing the deployment of the VM? So if this was the last CSE setup for the VM, would the VM provisioning be green?

We want this kind of approach because we have to carry out a number of long operations on behalf of the user, but if the provisioning of a VM times out then the deployment is flagged as failed on the portal, and the resource group deployment too of course.

Our marketplace solution is pretty complex and I thought of asking directly since I am still not sure by looking at a number of attempts.

The contact person for our project is @isamllr .

**Comment by ahmetalpbalkan** [comment]
Hello @rvvincelli,

I am assuming you are using ARM template deployments to deploy VMs with CSE in them. When your entrypoint command returns after kicking off `do_something_taking_a_long_time` into the background (which I'm guessing in this case `file.sh`), CSE will collect the exit code of this bash script and report success/failure and report it to the API/portal etc so that rest of your template/VM deployment go ahead.

However I don't suggest forking processes into the background, unless you care about their results. If you add `set -e` to your script (which [you should](http://redsymbol.net/articles/unofficial-bash-strict-mode/)), an error in `do_something` will come up as a template deployment error. However an error in `do_something_taking_a_long_time` will not.

I can't imagine a case where you want to do some setup operation whose result you don’t care. You will have no way of knowing that command sent to the background has failed or not. So I suggest not using an approach to this. Why do you exactly want this?

**Comment by rvvincelli** [comment]
Hello @ahmetalpbalkan ,

Thank you so much for your quick response!

Yes we are in ARM mode using the JSON template - this is currently in review by the Azure Marketplace team.

Ok, great, so the behavior is what I expected, which makes sense: when I hit the background function the script returns and the CSE instrumentation reads the exit status. Maybe there could have been some other machinery you know, I wanted to be sure.

About bash modes, we can have a long discussion of course. I feel it depends on the programming style; in the code we actually catch nonzero exits as needed.

I think our use case fits a scenario where such a background function is executed.
The solution basically installs an [Apache Ambari](http://ambari.apache.org) cluster. Ambari is the cluster manager of the Hortonworks Hadoop distribution. 
In Ambari you define a number of services, and at provisioning they are all started. Unfortunately, Ambari itself and a few services we ship are bugged - for a number of reasons the first installation attempt might fail. So, we want to retry and keep sending installation requests for the faulty services in continu via the Ambari API.
Now, this can be a lenghty process. And if a deployment on Azure is too long, it times out; we are now sure there is no way to configure a backend timeout. So, on one hand we want to return immediately to avoid Azure timeouts, on the other we also want the user to just sit and watch the Ambari installation complete, without the need of manual steps or even browser clicks, once he/she is able to connect. A background stratgy enables us to do so. These reattempt poller works via the Ambari API, and nothing can go wrong, reasonably. If, in absurdu, something does go wrong, the user will have to finish off the Ambari installation him/her self. So yes we do not care about the results really.

If you are interested in the code, let me know and I'll show it to you.

Thank you!!
