### ISSUE TITLE
enableInternalDNSCheck

### ISSUE THREAD

**Issue by mschirrmeister** [Azure/custom-script-extension-linux#65]
In the old custom script extension (Microsoft.OSTCExtensions.CustomScript 1.5), there was an option `enableInternalDNSCheck`. Which we used to avoid problems with dns timeouts. (https://github.com/Azure/azure-linux-extensions/issues/142)

It seems this option is not available in the new *2.0* version. Is the option not there, because this problem does no longer exists in 2.0, or is there another replacement?
handler.log has the following line, when I try to add this option.

```
time=2016-09-19T11:52:09Z version=v2.0.1/git@0f92134-clean operation=enable seq=0 event="failed to handle" error="failed to get configuration: json validation error: invalid public settings JSON: enableInternalDNSCheck: Additional property enableInternalDNSCheck is not allowed"
```

**Comment by mschirrmeister** [comment]
We had those dns issues recently, a few weeks ago, with version 1.5 of the custom script.
If those is no longer valid or the case, perfect. We will monitor the situation with version 2.0 and see how provisioning goes.

**Comment by ahmetalpbalkan** [comment]
@mschirrmeister This feature was added, mostly because the "internal" DNS check was broken (meaning VMs in the same Virtual Network could not talk to each other when they are booted). As far as I know, this is fixed in the infrastructure and when the VM boots, the DNS resolution should be enabled for the machine prior to boot.

Basically all this feature was doing was waiting `host "$(hostname)"` command worked. If you run into any issues resolving other VMs in the same VNET at the boot time, please let us know and I will have the networking team investigate the problem.

As a workaround, please add this to the beginning of your script if you hit the issue I described:

    while true; do host "$(hostname)"; ec=$?; if [ $ec -eq 0 ]; then break; fi; sleep 1; done
