### ISSUE TITLE
dpkg status database is locked by another process

### ISSUE THREAD

**Issue by wbuchwalter** [Azure/custom-script-extension-linux#82]
Moved from https://github.com/Azure/azure-linux-extensions/issues/291.

Hi,

I am deploying an ARM template ([you can find it here](https://gist.github.com/wbuchwalter/541fa85a9cc561c5656e411dae39afb2)) with a custom linux extension ([you can find it here](https://gist.github.com/wbuchwalter/cb41e1e782fce28041a90574663726fd)).
This extension is basically doing some `apt-get install` and then manually installing a package with `dpkg`.

The VM this extension is attached to is based on a custom image (generalized from Ubuntu 16.04).

The extension will fail on `dpkg`, with error:
`dpkg: error: dpkg status database is locked by another process`

- [handler.log](https://gist.github.com/wbuchwalter/0837dd02bf2e8e2bc8213ad67b5c3c1d)
- [waagent.log](https://gist.github.com/wbuchwalter/52756bfab7e94e3095e5935db71a7a43)

It's worth noting that while `apt-get install` seems to work fine, it also complains similarily:
`E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?`

I did not install any other extensions.

I added a `ps ax | grep dpkg` in the script to see if something else was using dpkg, but it doesn't seems so.

If I add a `sleep 10m` at the start of my script everything works fine, so it seems that my custom extension is executed before the VM is fully ready.

Content of `/var/lib/waagent` for reference
```
884D28C1001CCA04E6DC7D86D49DDC11C806C6CB.crt  GoalState.2.xml                                         TransportPrivate.pem
884D28C1001CCA04E6DC7D86D49DDC11C806C6CB.prv  HostingEnvironmentConfig.xml                            WireServerEndpoint
Certificates.p7m                              Incarnation                                             custom-script
Certificates.pem                              Microsoft.Azure.Extensions.CustomScript-2.0.2           events
Certificates.xml                              Microsoft.Azure.Extensions.CustomScript.2.manifest.xml  handler_state
ExtensionsConfig.1.xml                        Microsoft.Azure.Extensions__CustomScript__2.0.2.zip     ovf-env.xml
ExtensionsConfig.2.xml                        SharedConfig.xml                                        provisioned
GoalState.1.xml                               TransportCert.pem
```

Thanks

**Comment by ahmetalpbalkan** [comment]
@wbuchwalter this error happens often often there's another extension implicitly installed on your machine and it's going through another installation with `apt` concurrently. However your /var/lib/waagent folder shows only CustomScript extension, so I'm guessing that's not the case.

Couple of things to note, you don't need to use `sudo` in your script (your script runs as root) and you can make use of `set -e` mode so that if any command in your script fails, it'll exit immediately (bash does not do this by default). [[more info]](http://redsymbol.net/articles/unofficial-bash-strict-mode/) This may help you debug the issue better.

Another possibility is, maybe you ran some apt based commands and while you're running them CustomScript kicked in. This would also cause the lock file issue. Do you reuse the same VM or create a new VM every time you deploy the template?

It might be helpful to see apt and dpkg logs (they should be under /var/log as well). Those can give us a good idea of timeline of dpkg/apt events.

**Comment by wbuchwalter** [comment]
Hey Ahmet!
> Do you reuse the same VM or create a new VM every time you deploy the template?

The template is deployed in a new resource group every time, so no interference.

> I'm fairly certain some other installation/update was going on simultaneously as CustomScript.

So in [apt/history.log](https://gist.github.com/wbuchwalter/419e9e7e465f08fab32c445483bb0040), we actually see `Commandline: /usr/bin/unattended-upgrade` being executed around the same time, but no sign of the `apt-get install` command executed by my script.  
Since this VM is from a custom image, is anything done to call `unattended-upgrade` the first time we create a VM based on an image? That would explain the issue.

[dpkg.log](https://gist.github.com/wbuchwalter/5bd7e36619574dca0b86d200efb357a2)

**Comment by ahmetalpbalkan** [comment]
It looks like you have found the culprit. I am not familiar with the images as much, so I can suggest the following:

- move the `unattended-upgrade` to your CustomScript (assuming is executed only once)
- configure the `unattended-upgrade` so that it does not run until either first N minutes of the VM or your CustomScript is completed
- add retries around `apt-get install` (or `dpkg -i`) logic in your bash script

This should solve your issue. We don't encounter this as I believe our stock base distro images do not have `unattended-upgrade` enabled.
