### ISSUE TITLE
Support multiple commands

### ISSUE THREAD

**Issue by clangaxon** [Azure/custom-script-extension-linux#91]
It would be very handy to support an array of commandToExecute that were executed in a specific order so that we could inline a number of commands without worrying about the possible complexities of downloading a script from an external source - NSGs, proxies, security, etc.

**Comment by boumenot** [comment]
Thank you for logging an issue!

There was similar bug logged against V1 of CustomScript, see https://github.com/Azure/azure-linux-extensions/issues/216. I don't know if you're targeting a cloud-init enabled distro or not, but CustomData may be a viable alternative if you are. It would be a breaking change to support an array vs. the string, so there are no plans at this time.  I agree that there is considerable more work involved when you just want to execute script instead of a command, and we should make that easier.

**Comment by clang-taser** [comment]
Yes, I'd have to +1 #216 :)  We're using OpenLogic images which don't appear to have cloud init installed for whatever reason (odd, since CentOS images on AWS have it enabled by default). 

As for a breaking change, seems like it could be called commandsToExecute and commandToExecute deprecated. :)

**Comment by hoangpx** [comment]
Can I do "&& or ;" inside commandsToExecute ?  Ex : "mkdir h && mkdir g"

**Comment by boumenot** [comment]
Yes, this is an example in the README.md.

**Comment by boumenot** [comment]
v2.0.4 adds support for executing an actual script.  There is no need to craft a settings that downloads scripts from blob storage, and a commandToExecute.

**Comment by parthasarathi204** [comment]
is this version 2.0.4  available now for windows?

**Comment by varnav** [comment]
Use this hack for Windows to run multiple commands:

`"commandToExecute": "powershell.exe -Command \"netsh advfirewall firewall add rule name='Windows Remote Management (HTTPS-In)' dir=in remoteip='10.0.0.0/8' action=allow protocol=TCP localport=5986; winrm quickconfig -transport:https -q\""`
